obgen data/smi_files_reduit/rugulin.smi > data/smi_files_reduit/rugulin.mol
obgen data/smi_files_reduit/tsukushinamine_A.smi > data/smi_files_reduit/tsukushinamine_A.mol
obgen data/smi_files_reduit/artelein.smi > data/smi_files_reduit/artelein.mol
obgen data/smi_files_reduit/trichodimerol.smi > data/smi_files_reduit/trichodimerol.mol
obgen data/smi_files_reduit/kopsinitarine_A.smi > data/smi_files_reduit/kopsinitarine_A.mol
obgen data/smi_files_reduit/sampsonione_A.smi > data/smi_files_reduit/sampsonione_A.mol
obgen data/smi_files_reduit/bielschowskysin.smi > data/smi_files_reduit/bielschowskysin.mol
obgen data/smi_files_reduit/scholarisine_A.smi > data/smi_files_reduit/scholarisine_A.mol
obgen data/smi_files_reduit/jiadifenolide.smi > data/smi_files_reduit/jiadifenolide.mol
obgen data/smi_files_reduit/platensimycin.smi > data/smi_files_reduit/platensimycin.mol
obgen data/smi_files_reduit/hippolachnin_A.smi > data/smi_files_reduit/hippolachnin_A.mol
obgen data/smi_files_reduit/borneol.smi > data/smi_files_reduit/borneol.mol
obgen data/smi_files_reduit/atropurpuran.smi > data/smi_files_reduit/atropurpuran.mol
obgen data/smi_files_reduit/jatamanin_H.smi > data/smi_files_reduit/jatamanin_H.mol
obgen data/smi_files_reduit/varioxepine_A.smi > data/smi_files_reduit/varioxepine_A.mol
obgen data/smi_files_reduit/illihenin_A.smi > data/smi_files_reduit/illihenin_A.mol
obgen data/smi_files_reduit/arboduridine.smi > data/smi_files_reduit/arboduridine.mol
obgen data/smi_files_reduit/epicoccane_C.smi > data/smi_files_reduit/epicoccane_C.mol
obgen data/smi_files_reduit/kopsine.smi > data/smi_files_reduit/kopsine.mol
obgen data/smi_files_reduit/harringtonolide.smi > data/smi_files_reduit/harringtonolide.mol
obgen data/smi_files_reduit/daphniacetal_A.smi > data/smi_files_reduit/daphniacetal_A.mol
obgen data/smi_files_reduit/alternarilactone_A.smi > data/smi_files_reduit/alternarilactone_A.mol
obgen data/smi_files_reduit/nesteretal_A.smi > data/smi_files_reduit/nesteretal_A.mol
obgen data/smi_files_reduit/punctaporonin_U.smi > data/smi_files_reduit/punctaporonin_U.mol
obgen data/smi_files_reduit/illisimonin_A.smi > data/smi_files_reduit/illisimonin_A.mol
obgen data/smi_files_reduit/astellolide_R.smi > data/smi_files_reduit/astellolide_R.mol
obgen data/smi_files_reduit/arthpyrone_M.smi > data/smi_files_reduit/arthpyrone_M.mol
obgen data/smi_files_reduit/aconicumine_A.smi > data/smi_files_reduit/aconicumine_A.mol
obgen data/smi_files_reduit/arsenicin_A.smi > data/smi_files_reduit/arsenicin_A.mol
obgen data/smi_files_reduit/euphylonoid_A.smi > data/smi_files_reduit/euphylonoid_A.mol
obgen data/smi_files_reduit/bislangduoid_A.smi > data/smi_files_reduit/bislangduoid_A.mol
obgen data/smi_files_reduit/alstoscholarisine_K.smi > data/smi_files_reduit/alstoscholarisine_K.mol
obgen data/smi_files_reduit/granatripodin_B.smi > data/smi_files_reduit/granatripodin_B.mol
obgen data/smi_files_reduit/meloyinnanine_A.smi > data/smi_files_reduit/meloyinnanine_A.mol
obgen data/smi_files_reduit/longifolactone_F.smi > data/smi_files_reduit/longifolactone_F.mol
obgen data/smi_files_reduit/aplydactone.smi > data/smi_files_reduit/aplydactone.mol
obgen data/smi_files_reduit/tabernabovine_B.smi > data/smi_files_reduit/tabernabovine_B.mol
obgen data/smi_files_reduit/asperazine_D.smi > data/smi_files_reduit/asperazine_D.mol
obgen data/smi_files_reduit/inaequalisine_A.smi > data/smi_files_reduit/inaequalisine_A.mol
obgen data/smi_files_reduit/strepantibin_A.smi > data/smi_files_reduit/strepantibin_A.mol
obgen data/smi_files_reduit/KB343.smi > data/smi_files_reduit/KB343.mol
obgen data/smi_files_reduit/geopyxin_A.smi > data/smi_files_reduit/geopyxin_A.mol
obgen data/smi_files_reduit/lobarialide_A.smi > data/smi_files_reduit/lobarialide_A.mol
obgen data/smi_files_reduit/cycloaplysinopsin_A.smi > data/smi_files_reduit/cycloaplysinopsin_A.mol
obgen data/smi_files_reduit/aleutianamine.smi > data/smi_files_reduit/aleutianamine.mol
obgen data/smi_files_reduit/peshawaraquinone.smi > data/smi_files_reduit/peshawaraquinone.mol
obgen data/smi_files_reduit/retigeranic_acid_A.smi > data/smi_files_reduit/retigeranic_acid_A.mol
obgen data/smi_files_reduit/scabrolide_A.smi > data/smi_files_reduit/scabrolide_A.mol
obgen data/smi_files_reduit/greenwaylactam_A.smi > data/smi_files_reduit/greenwaylactam_A.mol
obgen data/smi_files_reduit/ineleganolide.smi > data/smi_files_reduit/ineleganolide.mol
obgen data/smi_files_reduit/pedrolide.smi > data/smi_files_reduit/pedrolide.mol
obgen data/smi_files_reduit/anislactone_B.smi > data/smi_files_reduit/anislactone_B.mol
obgen data/smi_files_reduit/ceforalide_F.smi > data/smi_files_reduit/ceforalide_F.mol
obgen data/smi_files_reduit/malibatol_A.smi > data/smi_files_reduit/malibatol_A.mol
obgen data/smi_files_reduit/incargranine_A.smi > data/smi_files_reduit/incargranine_A.mol
obgen data/smi_files_reduit/brevianamide_A.smi > data/smi_files_reduit/brevianamide_A.mol
obgen data/smi_files_reduit/ulodione_A.smi > data/smi_files_reduit/ulodione_A.mol
obgen data/smi_files_reduit/stemoamide.smi > data/smi_files_reduit/stemoamide.mol
obgen data/smi_files_reduit/schweinfurthin_Q.smi > data/smi_files_reduit/schweinfurthin_Q.mol
obgen data/smi_files_reduit/daphnodorin_A.smi > data/smi_files_reduit/daphnodorin_A.mol
obgen data/smi_files_reduit/volvaltrate_A.smi > data/smi_files_reduit/volvaltrate_A.mol
obgen data/smi_files_reduit/galanthamine.smi > data/smi_files_reduit/galanthamine.mol
obgen data/smi_files_reduit/havellockate.smi > data/smi_files_reduit/havellockate.mol
obgen data/smi_files_reduit/myriberine.smi > data/smi_files_reduit/myriberine.mol
obgen data/smi_files_reduit/myrioxazine_A.smi > data/smi_files_reduit/myrioxazine_A.mol
obgen data/smi_files_reduit/epicoccin_G.smi > data/smi_files_reduit/epicoccin_G.mol
obgen data/smi_files_reduit/biyouyanagin_A.smi > data/smi_files_reduit/biyouyanagin_A.mol
obgen data/smi_files_reduit/aberrarone.smi > data/smi_files_reduit/aberrarone.mol
obgen data/smi_files_reduit/daphmanidin.smi > data/smi_files_reduit/daphmanidin.mol
obgen data/smi_files_reduit/spirotryprostatin_B.smi > data/smi_files_reduit/spirotryprostatin_B.mol
obgen data/smi_files_reduit/phorbol.smi > data/smi_files_reduit/phorbol.mol
obgen data/smi_files_reduit/xiamycin_A.smi > data/smi_files_reduit/xiamycin_A.mol
obgen data/smi_files_reduit/okaramine_N.smi > data/smi_files_reduit/okaramine_N.mol
obgen data/smi_files_reduit/chartelline_C.smi > data/smi_files_reduit/chartelline_C.mol
obgen data/smi_files_reduit/vinigrol.smi > data/smi_files_reduit/vinigrol.mol
obgen data/smi_files_reduit/maoecrystal.smi > data/smi_files_reduit/maoecrystal.mol
obgen data/smi_files_reduit/pallambin_C.smi > data/smi_files_reduit/pallambin_C.mol
obgen data/smi_files_reduit/taxuyunnanine_D.smi > data/smi_files_reduit/taxuyunnanine_D.mol
obgen data/smi_files_reduit/ingenol.smi > data/smi_files_reduit/ingenol.mol
obgen data/smi_files_reduit/cortistatin_A.smi > data/smi_files_reduit/cortistatin_A.mol
obgen data/smi_files_reduit/santonin.smi > data/smi_files_reduit/santonin.mol
